---
version: "3"

services:
    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: tagower/iss_tracker:midterm
        volumes:
            - ./config.yaml:/config.yaml
